version: "3.0"
### Environment Variables ###
# USER_DIR=~/docker_userdir
# DOCKER_USER  = 0
# DOCKER_GROUP = 0
# VNC_PORT     = 9999 ## port of browser_vnc
# VNC_PORT2    = 19999 ## port of browser_vnc
# JUPYTER_PORT = 8888 ## port of jupyter
# JUPYTER_TOKEN = ''  ## token (password) to login jupyter
# DOCKER_DISPLAY = 10
# DOCKER_DISPLAY2 = 11
# REPO=irslrepo/
###
services:
  xservera:
    image: ${REPO:-irslrepo/}browser_vnc:20.04
    # ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "${VNC_PORT:-9999}:80"
    command: [ supervisord, -c, /app/supervisord.conf ]
    environment:
      - DISPLAY=:${DOCKER_DISPLAY:-10}
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X${DOCKER_DISPLAY:-10}"]
      interval: "2s"
      retries: 20
    volumes:
      - 'tmpdir:/tmp/.X11-unix'
  xserverb:
    image: ${REPO:-irslrepo/}browser_vnc:20.04
    # ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "${VNC_PORT2:-19999}:80"
    command: [ supervisord, -c, /app/supervisord.conf ]
    environment:
      - DISPLAY=:${DOCKER_DISPLAY2:-11}
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X${DOCKER_DISPLAY2:-11}"]
      interval: "2s"
      retries: 20
    volumes:
      - 'tmpdir:/tmp/.X11-unix'
  main:
    image: ${REPO:-irslrepo/}irsl_hr4c:noetic
    security_opt:
      - seccomp:unconfined
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
    command: [ "jupyter", "lab", "--allow-root", "--no-browser", "--ip=0.0.0.0", "--port=8888", "--ServerApp.token='${JUPYTER_TOKEN:-}'", "--FileCheckpoints.checkpoint_dir=/tmp" ]
    environment:
      - DISPLAY=:${DOCKER_DISPLAY:-10}
      - DOCKER_ROS_SETUP=/hr4c_ws/devel/setup.bash
      - ROS_IP=localhost
      - ROS_MASTER_URI=http://localhost:11311
    working_dir: /userdir
    depends_on:
      - xservera
    volumes:
      - '${USER_DIR:-~/docker_userdir}:/userdir'
      - 'tmpdir:/tmp/.X11-unix'
volumes:
  tmpdir:
